project:
  type: website
  output-dir: docs

website:
  title: "getrealwiki"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - about-get-real.qmd
      - faq.qmd
      - href: data-entry-report.html
        text: Data Entry Report
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

