project:
  type: website
  output-dir: docs
  

website:
  title: "getrealwiki"
  page-navigation: true
  navbar:
      right:
        - text: "Home"
          file: index.qmd
        - text: "About"
          file: faq.qmd
        - text: "Reports"
          file: data-entry-report.html
          
page-footer:
    left: |
      Copyright by Kevin Gilds 2023 
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub https://github.com/kgilds/getrealwiki) 
  
 

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

