project:
  type: website
  output-dir: docs
  

website:
  title: "getrealwiki"
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    left: |
      Copyright by Kevin Gilds 2023 
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub https://github.com/kgilds/getrealwiki) 
  
navbar:
    left:
      - href: index.qmd
        text: Home
      - faq.qmd
      - about-get-real.qmd
      - href: data-entry-report.html
        text: Data Entry Report

      

format:
  html:
    theme: minty
    css: styles.css
    toc: false

editor: visual

