project:
  type: website
  output-dir: docs
  

website:
  title: "getrealwiki"
  page-navigation: true
  site-url: "https://kgilds.github.io/getrealwiki"
 
  navbar:
      right:
        - text: "Home"
          file: index.qmd
        - text: "About"
          file: faq.qmd
        - text: "News"
          file: news/index.qmd
        - text: "Reports"
          file: data-entry-report.html
          
  sidebar:
    - title: "About"
      collapse-level: 2
      
      contents:
        - faq.qmd
        - about-evaluator.qmd
        - about-get-real.qmd
        
          
          
  page-footer:
    left: |
      Copyright by Kevin Gilds 2023 
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub https://github.com/kgilds/getrealwiki) 
  
 

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

